trigger:
  branches:
    include:
      - main  # Trigger pipeline when changes are merged into 'main' branch

variables:
  - group: DeploymentVariables

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu machine to run the pipeline

stages:
- stage: Build
  displayName: "Build and Publish Artifacts"
  jobs:
  - job: BuildJob
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
      displayName: 'Set Python Version'

    - script: pip install -r requirements.txt
      displayName: 'Install Dependencies'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'  # Archive the entire source folder
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/deployment_package_$(Build.BuildId).zip'
        replaceExistingArchive: true
      displayName: 'Create Deployment Archive'

    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'DeploymentPackage'  # ✅ Single artifact containing everything
        targetPath: '$(Build.ArtifactStagingDirectory)/deployment_package_$(Build.BuildId).zip'
      displayName: 'Publish Deployment Package'
    #  # Publish Python scripts
    # - task: PublishPipelineArtifact@1
    #   inputs:
    #     targetPath: 'scripts'  # Publish the 'scripts' folder as an artifact
    #     artifact: 'deployment-scripts'  # Name of the published artifact
    #     publishLocation: 'pipeline'
    #   displayName: 'Publish Scripts as Artifact'

- stage: Deploy
  displayName: "Deploy and Release"
  dependsOn: Build
  jobs:
  - template: release-pipeline.yml